name: Python CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip   # built-in pip cache
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint (pylint, if installed)
        run: |
          python - <<'PY'
          import pkgutil, sys, subprocess
          sys.exit(0) if pkgutil.find_loader('pylint') is None else subprocess.call(['pylint','**/*.py'])
          PY

      - name: Run tests (pytest)
        run: |
          python -m pytest -q
